language: python
sudo: true
dist: xenial
arch:
    - amd64
    - arm64
python:
  - 3.8
  
git:
  depth: 99999

install: "pip install -r requirements.txt"

script:
  - make test_coverage
after_success:
  coveralls
